# Generated by Django 3.1.2 on 2021-05-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=250)),
                ('output', models.TextField(blank=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=None, editable=False)),
                ('completed_at', models.DateTimeField(default=None, editable=False)),
            ],
        ),
    ]
