# Generated by Django 3.1.2 on 2021-05-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuejob',
            name='started_at',
            field=models.DateTimeField(default=None, editable=False),
        ),
    ]
