# Generated by Django 3.1.2 on 2021-05-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_queuejob_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuejob',
            name='completed_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='queuejob',
            name='created_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='queuejob',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuejob',
            name='started_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
