# Generated by Django 3.1.2 on 2021-05-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20210517_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuejob',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
