# Generated by Django 3.1.2 on 2021-03-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_auto_20200902_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(default=None, editable=False)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='order.order')),
            ],
        ),
    ]
