# Generated by Django 3.1.2 on 2021-03-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_ordersync'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersync',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordersync',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='syncssy', to='order.order'),
        ),
    ]
